### ISSUE TITLE
Can not open HEVC video

### ISSUE THREAD

**Issue by triuk** [nalsai/AegisubFlatpak#4]
Hi, thanks for this. Almost lifesaver, one issue though.
I can load h264 video, but loading hevc gives me:
```
YUV4MPEG: video is not in supported format.
FFmpegSource: video is not in supported format.
```

The Windows version and Aegisub from PPA (still not released for 22.04) can open the video. Maybe the flatpak has included old ffmpeg?

**Comment by nalsai** [comment]
The flatpak uses the org.freedesktop.Platform.ffmpeg-full extension. Can you try running `flatpak install org.freedesktop.Platform.ffmpeg-full//21.08` to make sure it's installed correctly and the correct version. Sometimes it doesn't install it together and I'm not sure how to make it do that. 

I've used it multiple times with hevc without any issues, but I'll do some more testing tomorrow. Maybe you can send me an example file, you're having issues with? I at least need the mediainfo to see the exact format of the file.

**Comment by triuk** [comment]
The command above helped. I let it install from (system) repository. Thanks very much for the quick reply! Just in time :)
BTW it is an anime HEVC rls from Judas group.
